[book]
title = "Fobos Documentation"
authors = ["Fobos contributors"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/joaogabrielfer/blorp"
